p8105_hw6_cj2793
================
Chenyu Jin
2024-11-20

``` r
library(tidyverse)
library(modelr)
library(mgcv)
set.seed(1)
```

## Problem 2

### 1. Import and clean data

``` r
homicide_df = read_csv(file = "data/homicidedata.csv", na = c("Unknown", "NA", "")) |>
  mutate(reported_date = as.Date(as.character(reported_date), format = "%Y%m%d"))
```

    ## Rows: 52179 Columns: 12
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (8): uid, victim_last, victim_first, victim_race, victim_sex, city, stat...
    ## dbl (4): reported_date, victim_age, lat, lon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
homicide_df <- homicide_df |>
  mutate(
    city_state = str_c(city, state, sep = ", "),
    solved = if_else(disposition == "Closed by arrest", 1, 0),
    victim_age = as.numeric(victim_age)
  ) |>
  filter(
    !city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"),
    victim_race %in% c("White", "Black")
  )
```

### 2. logistic regression for Baltimore, MD

``` r
baltimore_df <- homicide_df |>
  filter(city_state == "Baltimore, MD")
```

``` r
logistic_model <- glm(solved ~ victim_age + victim_sex + victim_race, 
                      data = baltimore_df, family = binomial())
```

``` r
logistic_model |>
  broom::tidy(conf.int = TRUE) |>
  filter(term == "victim_sexMale") |> 
  mutate(
    OR = exp(estimate),
    CI_low = exp(conf.low),
    CI_high = exp(conf.high)
  ) |> 
  select(OR, CI_low, CI_high) |> 
  knitr::kable(digits = 3)
```

|    OR | CI_low | CI_high |
|------:|-------:|--------:|
| 0.426 |  0.324 |   0.558 |

The adjusted odds ratio for solving homicides comparing male victims to
female victims is 0.426 (CI: 0.324~0.558), keeping all other variables
fixed.

### 3. logistic regression for each of the cities

``` r
city_models <- homicide_df |>
  group_by(city_state) |>
  nest() |>
  mutate(
    model = map(data, ~ glm(solved ~ victim_age + victim_sex + victim_race, 
                            data = ., family = binomial())),
    results = map(model, ~ broom::tidy(.x, conf.int = TRUE) |>
                    filter(term == "victim_sexMale") |>
                    mutate(
                      OR = exp(estimate),
                      CI_low = exp(conf.low),
                      CI_high = exp(conf.high)
                    ) |>
                    select(OR, CI_low, CI_high))
  ) |>
  unnest(results) |>
  select(city_state, OR, CI_low, CI_high)
```

``` r
city_models |>
  knitr::kable(digits = 3)
```

| city_state         |    OR | CI_low | CI_high |
|:-------------------|------:|-------:|--------:|
| Albuquerque, NM    | 1.767 |  0.825 |   3.762 |
| Atlanta, GA        | 1.000 |  0.680 |   1.458 |
| Baltimore, MD      | 0.426 |  0.324 |   0.558 |
| Baton Rouge, LA    | 0.381 |  0.204 |   0.684 |
| Birmingham, AL     | 0.870 |  0.571 |   1.314 |
| Boston, MA         | 0.667 |  0.351 |   1.260 |
| Buffalo, NY        | 0.521 |  0.288 |   0.936 |
| Charlotte, NC      | 0.884 |  0.551 |   1.391 |
| Chicago, IL        | 0.410 |  0.336 |   0.501 |
| Cincinnati, OH     | 0.400 |  0.231 |   0.667 |
| Columbus, OH       | 0.532 |  0.377 |   0.748 |
| Denver, CO         | 0.479 |  0.233 |   0.962 |
| Detroit, MI        | 0.582 |  0.462 |   0.734 |
| Durham, NC         | 0.812 |  0.382 |   1.658 |
| Fort Worth, TX     | 0.669 |  0.394 |   1.121 |
| Fresno, CA         | 1.335 |  0.567 |   3.048 |
| Houston, TX        | 0.711 |  0.557 |   0.906 |
| Indianapolis, IN   | 0.919 |  0.678 |   1.241 |
| Jacksonville, FL   | 0.720 |  0.536 |   0.965 |
| Las Vegas, NV      | 0.837 |  0.606 |   1.151 |
| Long Beach, CA     | 0.410 |  0.143 |   1.024 |
| Los Angeles, CA    | 0.662 |  0.457 |   0.954 |
| Louisville, KY     | 0.491 |  0.301 |   0.784 |
| Memphis, TN        | 0.723 |  0.526 |   0.984 |
| Miami, FL          | 0.515 |  0.304 |   0.873 |
| Milwaukee, wI      | 0.727 |  0.495 |   1.054 |
| Minneapolis, MN    | 0.947 |  0.476 |   1.881 |
| Nashville, TN      | 1.034 |  0.681 |   1.556 |
| New Orleans, LA    | 0.585 |  0.422 |   0.812 |
| New York, NY       | 0.262 |  0.133 |   0.485 |
| Oakland, CA        | 0.563 |  0.364 |   0.867 |
| Oklahoma City, OK  | 0.974 |  0.623 |   1.520 |
| Omaha, NE          | 0.382 |  0.199 |   0.711 |
| Philadelphia, PA   | 0.496 |  0.376 |   0.650 |
| Pittsburgh, PA     | 0.431 |  0.263 |   0.696 |
| Richmond, VA       | 1.006 |  0.483 |   1.994 |
| San Antonio, TX    | 0.705 |  0.393 |   1.238 |
| Sacramento, CA     | 0.669 |  0.326 |   1.314 |
| Savannah, GA       | 0.867 |  0.419 |   1.780 |
| San Bernardino, CA | 0.500 |  0.166 |   1.462 |
| San Diego, CA      | 0.413 |  0.191 |   0.830 |
| San Francisco, CA  | 0.608 |  0.312 |   1.155 |
| St. Louis, MO      | 0.703 |  0.530 |   0.932 |
| Stockton, CA       | 1.352 |  0.626 |   2.994 |
| Tampa, FL          | 0.808 |  0.340 |   1.860 |
| Tulsa, OK          | 0.976 |  0.609 |   1.544 |
| Washington, DC     | 0.691 |  0.466 |   1.014 |

### 4. Create a plot to visualize the ORs and CIs

``` r
city_models |>
  ggplot(aes(x = reorder(city_state, OR), y = OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = CI_low, ymax = CI_high), width = 0.2) +
  labs(
    title = "Estimated Odds Ratios for Solving Homicides by City",
    x = "City, State",
    y = "Odds Ratio (Male vs Female Victims)"
  ) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

![](p8105_hw6_cj2793_files/figure-gfm/plot%20for%20problem2-1.png)<!-- -->

The plot displays the estimated odds ratios (ORs) for solving homicides
comparing male victims to female victims across different cities, with
corresponding confidence intervals (CIs). Many cities have confidence
intervals that cross 1, indicating no significant difference in solving
rates between male and female victims. Wide confidence intervals suggest
high variability in some cities such as Albuquerque, NM; Stockton, CA;
and Fresno, CA.

## Problem 3

### 1. Import and clean data

``` r
birthweight_df <- read_csv("data/birthweightdata.csv")
```

    ## Rows: 4342 Columns: 20
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (20): babysex, bhead, blength, bwt, delwt, fincome, frace, gaweeks, malf...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
birthweight_df <- birthweight_df  |> 
  janitor::clean_names() |>
  mutate(
    babysex = 
        case_match(babysex,
            1 ~ "male",
            2 ~ "female"
        ),
    babysex = fct_infreq(babysex),
    frace = 
        case_match(frace,
            1 ~ "white",
            2 ~ "black", 
            3 ~ "asian", 
            4 ~ "puerto rican", 
            8 ~ "other"),
    frace = fct_infreq(frace),
    mrace = 
        case_match(mrace,
            1 ~ "white",
            2 ~ "black", 
            3 ~ "asian", 
            4 ~ "puerto rican",
            8 ~ "other"),
    mrace = fct_infreq(mrace),
    malform = as.logical(malform)) |>
  drop_na()
```

### 2. Propose a regression model for birthweight

``` r
birthweight_model <- lm(bwt ~ babysex + bhead + blength + delwt + fincome + frace + gaweeks + malform + menarche + mheight + momage + mrace + parity + pnumlbw + pnumsga + ppbmi + ppwt + smoken + wtgain, data = birthweight_df)

summary(birthweight_model)
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ babysex + bhead + blength + delwt + fincome + 
    ##     frace + gaweeks + malform + menarche + mheight + momage + 
    ##     mrace + parity + pnumlbw + pnumsga + ppbmi + ppwt + smoken + 
    ##     wtgain, data = birthweight_df)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1097.68  -184.86    -3.33   173.09  2344.15 
    ## 
    ## Coefficients: (3 not defined because of singularities)
    ##                     Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)       -6265.3914   660.4011  -9.487  < 2e-16 ***
    ## babysexfemale        28.7073     8.4652   3.391 0.000702 ***
    ## bhead               130.7781     3.4523  37.881  < 2e-16 ***
    ## blength              74.9536     2.0217  37.075  < 2e-16 ***
    ## delwt                 4.1007     0.3948  10.386  < 2e-16 ***
    ## fincome               0.2898     0.1795   1.614 0.106551    
    ## fraceblack           14.3313    46.1501   0.311 0.756168    
    ## fracepuerto rican   -46.9962    44.6782  -1.052 0.292912    
    ## fraceasian           21.2361    69.2960   0.306 0.759273    
    ## fraceother            4.2969    74.0741   0.058 0.953745    
    ## gaweeks              11.5494     1.4654   7.882 4.06e-15 ***
    ## malformTRUE           9.7650    70.6259   0.138 0.890039    
    ## menarche             -3.5508     2.8951  -1.226 0.220083    
    ## mheight               9.7874    10.3116   0.949 0.342588    
    ## momage                0.7593     1.2221   0.621 0.534418    
    ## mraceblack         -151.4354    46.0453  -3.289 0.001014 ** 
    ## mracepuerto rican   -56.4787    45.1369  -1.251 0.210901    
    ## mraceasian          -91.3866    71.9190  -1.271 0.203908    
    ## parity               95.5411    40.4793   2.360 0.018307 *  
    ## pnumlbw                   NA         NA      NA       NA    
    ## pnumsga                   NA         NA      NA       NA    
    ## ppbmi                 4.3538    14.8913   0.292 0.770017    
    ## ppwt                 -3.4716     2.6121  -1.329 0.183913    
    ## smoken               -4.8544     0.5871  -8.269  < 2e-16 ***
    ## wtgain                    NA         NA      NA       NA    
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 272.5 on 4320 degrees of freedom
    ## Multiple R-squared:  0.7183, Adjusted R-squared:  0.717 
    ## F-statistic: 524.6 on 21 and 4320 DF,  p-value: < 2.2e-16

``` r
birthweight_df_1 <- birthweight_df |>
  add_predictions(birthweight_model) |>
  add_residuals(birthweight_model)

# Plot residuals against fitted values
ggplot(birthweight_df_1, aes(x = pred, y = resid)) +
  geom_point(alpha = 0.5) +
  geom_smooth() +
  labs(
    title = "Residuals vs Fitted Values",
    x = "Fitted Values (Predicted Birthweight)",
    y = "Residuals"
  ) +
  theme_minimal()
```

    ## `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'

![](p8105_hw6_cj2793_files/figure-gfm/plot1%20for%20problem3-1.png)<!-- -->

The full model for predicting birthweight (bwt) includes a comprehensive
set of variables that are believed to influence birthweight based on
biological, maternal, and socioeconomic factors. Key predictors include
baby characteristics such as sex, head circumference, and length at
birth, which directly relate to physical growth. Maternal factors such
as weight, height, age, and pre-pregnancy BMI are included because they
influence maternal health and fetal growth. Socioeconomic factors like
family income and parents’ race are added as proxies for access to
healthcare and resources, potentially impacting pregnancy outcomes.
Pregnancy-specific variables, such as gestational age, parity, weight
gain during pregnancy, and smoking behavior, are critical determinants
of fetal growth and overall birthweight. Together, these predictors
provide a broad and holistic view of factors affecting birthweight,
aiming to capture both direct and indirect influences.

### 3. Cross Validation

``` r
model_1 <- lm(bwt ~ blength + gaweeks, data = birthweight_df)

model_2 <- lm(bwt ~ bhead * blength * babysex, data = birthweight_df)

model_3 <- lm(bwt ~ babysex + bhead + blength + delwt + fincome + frace + gaweeks + malform + menarche + mheight + momage + mrace + parity + pnumlbw + pnumsga + ppbmi + ppwt + smoken + wtgain, data = birthweight_df)
```

``` r
set.seed(1)
cv_df <- crossv_mc(birthweight_df, 100) |>
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )

cv_df <- cv_df |>
  mutate(
    model_1 = 
      map(train, \(df) lm(bwt ~ blength + gaweeks, data = df)),
    model_2 = 
      map(train, \(df) lm(bwt ~ bhead * blength * babysex, data = df)),
    model_3 = 
      map(train, \(df) lm(bwt ~ babysex + bhead + blength + delwt + fincome + frace + gaweeks + malform + menarche + mheight + momage + mrace + parity + pnumlbw + pnumsga + ppbmi + ppwt + smoken + wtgain, data = df)),
    rmse_model_1 = 
      map2_dbl(model_1, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_model_2 = 
      map2_dbl(model_2, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_model_3 = 
      map2_dbl(model_3, test, \(mod, df) rmse(model = mod, data = df))
  )
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `rmse_model_3 = map2_dbl(model_3, test, function(mod, df)
    ##   rmse(model = mod, data = df))`.
    ## Caused by warning in `predict.lm()`:
    ## ! prediction from rank-deficient fit; attr(*, "non-estim") has doubtful cases

``` r
cv_df |> 
  select(starts_with("rmse")) |> 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") |> 
  mutate(model = fct_inorder(model)) |> 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```

![](p8105_hw6_cj2793_files/figure-gfm/plot2%20for%20problem3-1.png)<!-- -->

The violin plot shows the distribution of the RMSE (Root Mean Squared
Error) for each of the three models based on 100 cross-validation
iterations. Model 1, which only includes length at birth and gestational
age as predictors, has the largest variability and highest RMSE values,
indicating it performs the worst in predicting birthweight among the
three models. Model 2, which includes head circumference, length, sex,
and their interactions, shows an improvement in prediction accuracy,
with lower RMSE values and narrower variability. Model 3, which is the
full model incorporating a comprehensive set of predictors including
maternal, socioeconomic, and baby characteristics, performs the best
with the lowest RMSE and less variability, suggesting that including
more relevant features leads to a more accurate prediction of
birthweight.

Considering both model simplicity and predictive performance, Model 2 is
the best choice. Model 1 has the worst predictive performance, as
indicated by the highest RMSE, suggesting it lacks accuracy. While Model
3 offers the best predictive performance with the lowest RMSE, it is
highly complex, incorporating many variables, making it difficult to
interpret and potentially prone to overfitting. Model 2, on the other
hand, strikes a good balance between simplicity and predictive
performance.
